### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by JoshuaNovak919** [asanka-x/Phonegap-SMS#1]
Can you add an example of how to use this plugin? I'm having some issues trying to get it to work in my environment and it's hard to tell if it's something on my end or if i am using the plugin incorrectly. An example would help immensely.

**Comment by bau720123** [comment]
+1

**Comment by flynnwt** [comment]
I am trying it on Phonegap 3.3 (I had to change plugin.xml to allow cordova version >3.1.0).  I was getting a 'Class not found' error from the isSupported() call and found this in the log:
D/PluginManager(31799): exec() call to unknown plugin: SmsPlugin

Changing the line in plugin.xml to:
`<feature name="SmsPlugin">`
has fixed the problem.  I also received an SMS OK.

I'm new to phonegap but it also looks like the smsplugin.js should also be updated to support the newer module format.

**Comment by flynnwt** [comment]
One other thing - it looks like startReception() does not give an immediate 'OK' callback, but stopReception() does.  The first callback from startReception() occurs when a message is received.

**Comment by JoshuaNovak919** [comment]
@flynnwt Did you get the send method to work? If so, can you post a sample of the JS code you used? I can't tell if it is working or not thanks to my android phone not being connected to a network and it's driving me a bit nuts.

**Comment by flynnwt** [comment]
Yes, I had also tried a send() and it worked.  I wrote an angular sms service, but I'm not doing anything special in regard to the plugin calls:

```
    phonegapReady($scope).then(function initSMS() {
      sms.init(function(error, data) {
        if (sms.status().isSupported) {
          sms.startReceiving();
          sms.send('+19999999','Test from phonegap!','');
        }
      });
    });
```

Are you waiting for the deviceready event from phonegap?   `window.plugins.sms` is the plugin object.  My init:

```
        init: function(cb) {
          var me = 'sms.init';

          if (!window.plugins || !window.plugins.sms) {
            status.isSupported = false;
            status.error = 'Missing plugin!';
            logger.e(me, status.error);
            if (cb) {
              cb(status.error, null);
            }
            return;
          }
          sms = window.plugins.sms; // set up by Phonegap-SMS plugin
          status.error = 'Initializing...';
          status.isReceiving = false;
          sms.isSupported(
              function(result) {
                var me = 'sms.init';
                status.isSupported = result;
                status.error = null;
                logger.i(me, 'isSupported=' + status.isSupported);
                if (cb) {
                  cb(null, result);
                }
              },
              function(error) {
                var me = 'sms.init';
                status.isSupported = false;
                status.error = error;
                logger.e(me, status.error);
                if (cb) {
                  cb(error, null);
                }
              });
        },

```

**Comment by PatrickJAMET** [comment]
Hello it was still not working after updating feature name="SmsPlugin" in plugin.xml
To make it works I modified android.json in the plugin folder and also changed feature name="SMSPlugin" to feature name="SmsPlugin".

Working fine now, thank you for the plugin

**Comment by pauliktamas** [comment]
Hi!
I had the same issue, and the proper fix is the one mentioned by @SuperPatrick. If u change the plugin.xml feature name from "SMSPlugin" to "SmsPlugin" and then add the android platform, the android.json will be generated correctly.

Thanks!

**Comment by ghost** [comment]
Hi!!

I am using this line in config.xml: gap:plugin name="info.asankan.phonegap.smsplugin"
When I install the app it's all ok. I can see android alert me that the app can send and receive message. 
But when i call the isSupported() method, I was getting a 'Class not found' error.

I use phonegap build online to compile my app for android. I do not know how to implement the change on plugin.xml. 

Any of you can help me with that??

Thanks... !!!!

**Comment by pauliktamas** [comment]
As far as I know, you can't change anything if you use the phonegap remote build :\ what you could do, is to fork the repository, and commit your plugin.xml fix into your forked repo, and then use that in the config.xml (I haven't done it before, but I know it can be done)

Hope I could help :)

**Comment by Iknuts** [comment]
Hi, does this plugin allow you to send the SMS directly from the app? i dont want to use the onboard SMS application

On Saturday, June 21, 2014 4:28 PM, patomi notifications@github.com wrote:

As far as I know, you can't change anything if you use the phonegap remote build :\ what you could do, is to fork the repository, and commit your plugin.xml fix into your forked repo, and then use that in the config.xml (I haven't done it before, but I know it can be done)
Hope I could help :)

**Comment by pauliktamas** [comment]
It does have a send(number,message,successCallback(result),failureCallback(error)) method, so I guess it does, but I haven't tested it yet.

**Comment by ghost** [comment]
Thanks, pauliktamas. I already have the app complete. Forked the repository resolved the problem.

**Comment by asanka-x** [comment]
Hi all, really sorry about not being able to assist you, last few months I couldn't put any effort to this. A fix for this issue has been added. I'll update the phonegap with the fixes, so that you can use the cloud build. until that bare with the local build
